# config.toml

[data]
train_source_dir = "./Cao/models/mri_data/1.5T"  # Directory containing 1.5T images
train_target_dir = "./Cao/models/mri_data/3T"  # Directory containing 3T images
stats_file = "stats/dataset_stats.json"
valid_source_dir = "./Cao/models/mri_data/test_1.5T"  # Directory containing validation images
valid_target_dir = "./Cao/models/mri_data/test_3T"  # Directory containing test images
visualization_dir = "CycleGAN/visualizations"
batch_size = 8
num_workers = 8

[augmentation]
batch_size = 4
num_workers = 8
source_rotation_angle = 10.0
source_translation = 0.1
target_rotation_angle = 5.0
target_translation = 0.05

[model]
model = "TED"
features = 32
n_blocks = 4
ffn_scale = 2.0
cycle_weight = 10.0
identity_weight = 5.0
min_lr = 1e-6
lr = 1e-4

[discriminator]
model = "patch_gan"
in_channels = 1
features = 32
min_lr = 1e-6
lr = 1e-4


[training]
seed=42
max_epochs = 50
accelerator = "gpu"
devices = 1
precision = '16-mixed'
log_every_n_steps = 10
val_check_interval = 5
checkpoint_dir = "CycleGAN/checkpoints"
log_dir = "./CycleGAN/Logs"
experiment_name = "CycleGAN_MRI"