[paths]
source_dir = "./data/source-dir"
target_dir = "./data/target-dir"
log_dir = "./logs"
checkpoint_dir = "./checkpoints"

[training]
batch_size = 1
num_workers = 12
max_epochs = 20
accelerator = "gpu"
devices = 1
accumulate_grad_batches = 1
precision = '16-mixed'

[augmentation]
probability = 0.5

[generator]
model = "Unet"
in_channels = 1
out_channels = 1
features = 16
cycle_weight = 10.0
identity_weight = 5.0

[discriminator]
model = "patch_gan"
in_channels = 1
features = 16