import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, createTheme, MantineProvider } from '@mantine/core';
import { HeaderSimple } from "./lib/HeaderSimple";
import { HeroBullets } from "./lib/HeroBullets";
import { FooterCentered } from "./lib/FooterCentered";

const theme = createTheme({
  // Define your theme settings if needed
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider theme={theme}>
          <ColorSchemeScript />
          {children}
          <HeaderSimple />
          <HeroBullets />
          <FooterCentered />
        </MantineProvider>
      </body>
    </html>
  );
}
